title: OpenBeaker Portal
email: spam@openbeaker.org
description: >- 
  Portal. Open Portal. Better Portal.
baseurl: ""
url: "http://openbeaker.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  openbeaker

# Build settings
theme: "just-the-docs"
plugins:
  - jekyll-feed

  # Aux links for the upper right navigation
aux_links:
  "OpenBeaker on GitHub":
    - "//github.com/openbeaker"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
