title: OpenBeaker Portal
email: spam@openbeaker.org
description: >- 
  Portal. Open Portal. Better Portal.
baseurl: "/portal/"
url: "http://openbeaker.org"
github_username:  openbeaker

# Needed for github pages / preview
remote_theme: "pmarsceill/just-the-docs"
theme: "just-the-docs"

plugins:
  - jekyll-feed

aux_links:
  "OpenBeaker on GitHub":
    - "//github.com/openbeaker"
aux_links_new_tab: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
